### ISSUE TITLE
Quick review

### ISSUE THREAD

**Issue by Ray725** [spectatorpublishing/VES#62]
**DUE DATE OCTOBER 7, 2018**

Updated Designs:
https://drive.google.com/file/d/1WOZpchak1QC2MVoh1XoblapdFHTJbVRD/view?ts=5bb6b8f5

https://drive.google.com/file/d/1nvK3iKgYA8KUvVEkLRFHQvgR56NFiq41/view?ts=5bb6b777

**User Stories**

- As a user, I would like to be able to view qualitative student entered data on classes

- As a user, I would like to be able to sort classes and search for classes by data given by other students (difficulty, interest, amount of work)

**To-do**
- [x] Button on each class

- [x] When you click on button, you look into database and add data to a text box

- [x] API endpoint for database integration. Check link for review schema: https://docs.google.com/document/d/1BWJD-_qNwrSvvMiUCoG1BtqaPpf8mIJxj0Tp2Pk7Wuw/edit?usp=sharing

- [ ] Integrate these questions to pop up whenever someone chooses to review a class https://docs.google.com/document/d/18Uf5X_lwaF9r1zXP5q_d4qnrFIOEk3WHly55NB8aE_g/edit?usp=sharing

- [x] Make modal display reviews (Check UI card)
- [x] Make modal connect to GET endpoint.
- [x] Set up review submission modal.
- [x] Make modal connect to PUT endpoint.

![42449893_572062096545551_6397106938441629696_n](https://user-images.githubusercontent.com/13423095/46051007-24ba8180-c105-11e8-8608-8447634d8fbd.jpg)

**Comment by pecom** [comment]
Started looking into adding the modal popup on the button. No success :(
