### ISSUE TITLE
Vergil+ Tutorial

### ISSUE THREAD

**Issue by Ray725** [spectatorpublishing/VES#71]
**DUE DATE SEPTEMBER 30, 2018**

**User Stories**

- As a user, I would like to view a tutorial on Vergil+ features when I first download the extension, and would like to have the option to view that tutorial when I am lost

**To-do**
- [x] run it by Raymond

- [x] make new branch

- [x] Welcome

- [x] Open the sidebar

- [x] Smart search

- [x] Live class enrollments

- [x] Calendar export

- [ ] Ask billy how to get photos

- [ ] test a fresh install

- [ ] make pull request
