### ISSUE TITLE
Study Buddy

### ISSUE THREAD

**Issue by Ray725** [spectatorpublishing/VES#77]
**User Stories**

**To-do**

- [ ] Note: there is already a branch

- [ ] Add a "I would like a study buddy" button to the front end

- [ ] Finagle the coreswap endpoint into a study buddy endpoint

- [ ] Add the potential for study groups using a modal flow
