### ISSUE TITLE
Submit review tag system

### ISSUE THREAD

**Issue by pecom** [spectatorpublishing/VES#78]
Barebone tag system for submitting a review. On clicking "submit review" the modal popup should display a few tags ("nice", "funny", "mean", "strict", "boring", .... ) which are all checkbox buttons (can be true or false for each value and there can be multiple true values). There should also be a submit button that calls the relevant put review API endpoint and closes the modal popup

## To-do ##
- [x] Display basic tags with buttons
- [ ] Submit button closes modal
- [ ] Submit button calls relevant api endpoint with the data
- [ ] Formatting the JSONI
- [ ] Making three tabbed system
- [ ] Ensuring data is not lost

**Comment by WilliamChiu** [comment]
I vaguely recall @kyp2106 was working on submitting.
Now its a matter of formatting the JSON, producing a three tabbed system, and making sure we don't delete any of the data. - @pecom
