### ISSUE TITLE
Display review tag system

### ISSUE THREAD

**Issue by pecom** [spectatorpublishing/VES#79]
Barebones display review system. Upon clicking the review button, the modal should make the relevant get review API endpoint (should already be programmed). After making the call, get the tags and display the tags on the popup (limit to 5 for now).

Later on: Duplicate tags should not be displayed, instead there should be a number next to each tag representing how many times that tag was submitted. Once this is set up we should display the highest ones first. 

## To-do ##
- [x] Call relevant get review API endpoint
- [x] Display (at max) 5 tags
- [ ] Account for duplicate tags
- [ ] Sort tags based on count
